### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by merbin2012** [Sahil-Gupta584/video-downloader#1]
While add and run it show the following error

```
ReferenceError: process is not defined
    at node_modules/dotenv/lib/env-options.js (videos-downloader.js?v=0f827c79:401:5)
    at __require (chunk-G3PMV62Z.js?v=632c8dee:8:50)
    at videos-downloader.js?v=0f827c79:972:7
    at videos-downloader.js?v=0f827c79:976:3
cap.handleError @ VM3:816
videos-downloader.js?v=0f827c79:401 Uncaught ReferenceError: process is not defined
    at node_modules/dotenv/lib/env-options.js (videos-downloader.js?v=0f827c79:401:5)
    at __require (chunk-G3PMV62Z.js?v=632c8dee:8:50)
    at videos-downloader.js?v=0f827c79:972:7
    at videos-downloader.js?v=0f827c79:976:3
```

**Comment by Sahil-Gupta584** [comment]
issue has been solved you can continue you project now onwards with latest version 1.0.3

**Comment by merbin2012** [comment]
@Sahil-Gupta584 Thanks for considering my query and the new update.
But this issue is still found, please check the below-attached image.

    import s from 'videos-downloader';

![1](https://github.com/user-attachments/assets/daba943a-e1fa-4797-aa14-9c9de93932fe)
![2](https://github.com/user-attachments/assets/0d615328-984a-4f46-9a5a-3daeab4e0acf)
